jupyterhub:
  ingress:
    enabled: true
    hosts:
      - ${binderhub_subdomain}.${binderhub_domain}
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: letsencrypt-production
    tls:
      - secretName: ${project_name}-secret-tls
        hosts:
          - ${binderhub_subdomain}.${binderhub_domain}
  #https://discourse.jupyter.org/t/pre-building-images-on-binderhub/4325/4
  prePuller:
    continuous:
      enabled: true
  hub:
    baseUrl: /jupyter/
    extraConfig:
      noAuthMetrics: |
        c.JupyterHub.authenticate_prometheus = False
    config:
      BinderSpawner:
        cors_allow_origin: '*'
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/hub/metrics"

  proxy:
    service:
      type: NodePort
  cull:
    timeout: 1800 #30min
    every: 30
    concurrency: 5 #to avoid Hub slow down, 5 concurrent processes
    maxAge: 28800 #8h
  singleuser:
    storage:
      type: none
      extraVolumes:
      - name: shared-data
        hostPath:
          path: /DATA
      extraVolumeMounts:
      - name: shared-data
        mountPath: /home/jovyan/data  # where each user can reach shared data
        readOnly : true
    memory:
       guarantee: 4G
       limit: 8G
    cpu:
       guarantee: 1
       limit: 2
    startTimeout: 3600 #1h
    #for repo2data https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-initcontainers
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html#about-user-storage-and-adding-files-to-it
  #schedule binderhub core pods just on master
  #https://github.com/alan-turing-institute/hub23-deploy/blob/main/deploy/prod.yaml#L56
  scheduling:
    corePods:
      nodeAffinity:
        matchNodePurpose: require
    userPods:
      nodeAffinity:
        matchNodePurpose: prefer

# BinderHub config
config:
  Launcher:
    launch_timeout: 3600 #1h
    retries: 10
  GitHubRepoProvider:
    banned_specs:
      - ^(?!roboneurolibre\/.*).*
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*
      - ^hmharshit/cn-ait.*
      - ^shishirchoudharygic/mltraining.*
      - ^hmharshit/mltraining.*
  BinderHub:
    hub_url: https://${binderhub_subdomain}.${binderhub_domain}/jupyter
    use_registry: true
    image_prefix: binder-registry.conp.cloud/binder-registry.conp.cloud/binder-
    cors_allow_origin: '*'
    banner_message: |
      <div style="text-align:center;"><img src="https://github.com/neurolibre/brand/blob/main/png/roboneuro_leaf.png?raw=true" style="height: 200px;"></img><p>Reserved for published neurolibre.org preprints.</p></div>

service:
  type: NodePort

ingress:
  enabled: true
  hosts:
    - ${binderhub_subdomain}.${binderhub_domain}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-production
  https:
    enabled: true
    type: nginx
  tls:
    - secretName: ${project_name}-secret-tls
      hosts:
        - ${binderhub_subdomain}.${binderhub_domain}